export const NAILY_PRISMA_BEFORE_LISTENER = '__NAILY_PRISMA_BEFORE_LISTENER__';
export const NAILY_PRISMA_AFTER_LISTENER = '__NAILY_PRISMA_AFTER_LISTENER__';

export const NAILY_PRISMA_LISTENER_ARGUMENT = '__NAILY_PRISMA_LISTENER_ARGUMENT__';

export const NAILY_PRISMA_OPTIONS = Symbol('__NAILY_PRISMA_OPTIONS__');
